# Generated by Django 3.2.20 on 2023-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='alien-emoji.png', upload_to='avatars/'),
        ),
    ]
