# Generated by Django 3.2.20 on 2023-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_auto_20230730_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
