# Generated by Django 3.2.20 on 2023-07-23 18:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
